# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CrossCorr <- function(TestSignal, TemplateSignal) {
    .Call('_SpecMatch_CrossCorr', PACKAGE = 'SpecMatch', TestSignal, TemplateSignal)
}

StarletWT <- function(X) {
    .Call('_SpecMatch_StarletWT', PACKAGE = 'SpecMatch', X)
}

StarletRC <- function(X) {
    .Call('_SpecMatch_StarletRC', PACKAGE = 'SpecMatch', X)
}

PMT <- function(X) {
    .Call('_SpecMatch_PMT', PACKAGE = 'SpecMatch', X)
}

PMTRC <- function(C, V) {
    .Call('_SpecMatch_PMTRC', PACKAGE = 'SpecMatch', C, V)
}

MAD <- function(X) {
    .Call('_SpecMatch_MAD', PACKAGE = 'SpecMatch', X)
}

MultiResSuppStarlet <- function(X, NoSimu) {
    .Call('_SpecMatch_MultiResSuppStarlet', PACKAGE = 'SpecMatch', X, NoSimu)
}

HardThreshold <- function(C, M) {
    .Call('_SpecMatch_HardThreshold', PACKAGE = 'SpecMatch', C, M)
}

sign <- function(x) {
    .Call('_SpecMatch_sign', PACKAGE = 'SpecMatch', x)
}

SoftThreshold <- function(C, M) {
    .Call('_SpecMatch_SoftThreshold', PACKAGE = 'SpecMatch', C, M)
}

