# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

StarletWT <- function(X) {
    .Call('_SpecMatch_StarletWT', PACKAGE = 'SpecMatch', X)
}

StarletRC <- function(X) {
    .Call('_SpecMatch_StarletRC', PACKAGE = 'SpecMatch', X)
}

PMT <- function(X) {
    .Call('_SpecMatch_PMT', PACKAGE = 'SpecMatch', X)
}

PMTRC <- function(C, V) {
    .Call('_SpecMatch_PMTRC', PACKAGE = 'SpecMatch', C, V)
}

MultiResSuppPMT <- function(X, SimNo) {
    .Call('_SpecMatch_MultiResSuppPMT', PACKAGE = 'SpecMatch', X, SimNo)
}

MultiResSuppStarlet <- function(X, SimNo) {
    .Call('_SpecMatch_MultiResSuppStarlet', PACKAGE = 'SpecMatch', X, SimNo)
}

